version: '3'
services:
  ripe-database-documentation:
    image: ripe-database-documentation
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ripe-database-documentation
    ports:
      - "8080:80"
